import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import HeaderTicket from "../componets/layouts/ticket-flow/Header-ticket";
import FooterTicket from "../componets/layouts/ticket-flow/Footer-ticket";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BilletLayout({ children }) {
  return (
    <>
      <HeaderTicket />
      <main>{children}</main>
      <FooterTicket />
    </>
  );
}
